//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Машина
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public int Номер_клиента { get; set; }
        public string ФИО { get; set; }
        public Nullable<double> Телефон { get; set; }
        public string Место_высадки { get; set; }
        public Nullable<double> Стоимость_проезда { get; set; }
    }
}
