//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Машина
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поездки
    {
        public int Номер_поездки { get; set; }
        public string Направление { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Пасажир_1 { get; set; }
        public string Пасажир_2 { get; set; }
        public string Пасажир_3 { get; set; }
        public string Пасажир_4 { get; set; }
        public double Баланс { get; set; }
    }
}
